// --- DOM Elements ---
export const video = document.getElementById("videoFeed");
export const canvas = document.getElementById("displayCanvas");
export const imageInput = document.getElementById("imageInput");
export const transitionCanvas = document.getElementById("transitionCanvas");
export const resToggleBtn = document.getElementById("resToggleBtn");
export const ditherToggleBtn = document.getElementById("ditherBtn");
export const reverseCameraBtn = document.getElementById("reverseCameraBtn");
export const shutterBtn = document.getElementById("shutterBtn");
export const palettePreview = document.getElementById("palettePreview");
export const modalContent = document.getElementById("modal-content");
export const loadBtn = document.getElementById("loadBtn");
export const infoModal = document.getElementById("infoModal");
export const closeButton = document.querySelectorAll(".close-button");
export const paletteModal = document.getElementById("paletteModal");
export const paletteGrid = document.getElementById("palette-grid");
export const settingsBtn = document.getElementById("settingsBtn");
